### ISSUE TITLE
iOS does not record locations

### ISSUE THREAD

**Issue by yomatters** [CUUATS/bikemoves#16]
This may be fixed by https://github.com/CUUATS/bikemoves/commit/180b912b5a14cfc95e5cd1c73e6a314d41525913. If not, it may be related to https://github.com/CUUATS/bikemoves/commit/a45655809dd6b34aeca7879f5fe43e52a47032b1 or https://github.com/CUUATS/bikemoves/commit/73b8da29fb7b115a3b66321a2d905dca317dc25b.

**Comment by jzeiders** [comment]
iOS GPS was always reporting not moving, disabled the movement check, doesn't appear to have caused any other problems.

**Comment by yomatters** [comment]
I'm surprised to hear that, because I'm fairly certain that it was reporting movement earlier. The plugin should report moving = true when the status is recording (and moving = false when the status is paused or stopped). I think we need some sort of movement check because otherwise locations that are returned by getCurrentPosition (e.g., the initial location used to center the map) are included in the trip.

**Comment by jzeiders** [comment]
Turns out that there is no correlation between moving = true and the speed of the device being > 0. It now records location data when either of those is true, this solved the issue partially, however iOS is still failing to record a majority of the points.
