### ISSUE TITLE
GPS location jumps after tapping the locate button

### ISSUE THREAD

**Issue by yomatters** [CUUATS/bikemoves#2]
In some instances the GPS stops updating for part of the trip. Tapping the "my location" button causes the trip to jump directly to the current location.
![screenshot_2016-03-30-10-01-28](https://cloud.githubusercontent.com/assets/218131/14254933/826b04ca-fa57-11e5-865f-09d77495fbb0.png)

**Comment by yomatters** [comment]
In some cases, tapping the locate button does not update the location. In this trip, only the first few seconds of the trip were recorded even though the play button was activated for the entire trip.
![screenshot_20160404-112615](https://cloud.githubusercontent.com/assets/218131/14255277/d650f738-fa58-11e5-9f03-04401a3fac4a.png)

**Comment by afekete** [comment]
I haven't experienced this personally. Perhaps the location accuracy was set to battery saving so it was trying to use wifi to locate you? Let me know if you continue experiencing this after the latest update which prompts for high accuracy gps
