### ISSUE TITLE
Trip recording does not start immediately

### ISSUE THREAD

**Issue by yomatters** [CUUATS/bikemoves#3]
The trip in the attached screenshot started north of Washington Street (marked as CR 1550 N in the map), but the GPS did not start recording until several blocks later. This may be a case where we need a better indication when the GPS is still acquiring a signal.
![screenshot_2016-03-30-10-00-07](https://cloud.githubusercontent.com/assets/218131/14255011/db6d03e8-fa57-11e5-89bd-d506afd41d12.png)

**Comment by afekete** [comment]
Trips can no longer be started until location accuracy is "good". Hopefully that fixes this problem. Let me know if it persists
