### ISSUE TITLE
Poor GPS accuracy creates an inconsistent trip path

### ISSUE THREAD

**Issue by yomatters** [CUUATS/bikemoves#4]
Inclusions of poor accuracy GPS points creates a trip path that appears to double back on itself. Points should be discarded if they do not meet an accuracy threshold.
![screenshot_20160404-112640](https://cloud.githubusercontent.com/assets/218131/14255789/675ba5e6-fa5b-11e5-867e-43bd44c95990.png)

**Comment by afekete** [comment]
Points with low accuracy should no longer be added to the path. Let me know if the problem persists
