### ISSUE TITLE
Previous trip map is not centered on the recorded route

### ISSUE THREAD

**Issue by yomatters** [CUUATS/bikemoves#5]
The route is visible only after panning/zooming to the location where the trip took place:

![screenshot_2016-04-20-14-23-03](https://cloud.githubusercontent.com/assets/218131/14687567/fb1c4092-0703-11e6-80f3-2139c022f287.png)

**Comment by afekete** [comment]
a1d3e5d57ea52d070b7a2c43b539d13262264d62
Im not sure if there's a reason that got commented out.
