### ISSUE TITLE
Bike facilities and bike racks are difficult to see on the map

### ISSUE THREAD

**Issue by yomatters** [CUUATS/bikemoves#7]
This map shows the colors that we usually use for bike facilities:

http://www.arcgis.com/home/webmap/viewer.html?url=https%3A%2F%2Futility.arcgis.com%2Fusrsvcs%2Fservers%2Fabeda57b97c84c4f88e7423585b3a087%2Frest%2Fservices%2FCCRPC%2FTrailsBikeways%2FMapServer%2F0&panel=gallery&suggestField=true

**Comment by afekete** [comment]
Are you referring to the transparent grey we use for bike paths?

**Comment by yomatters** [comment]
Based on the feedback from last Friday, I think we may need to switch to prerendered tiles for displaying features on the map. That will allow us to add sidewalks and other detailed datasets without exponentially increasing data usage. I'm working on setting up a tiled map service for that purpose. So, let's hold off on this issue for now.
