### ISSUE TITLE
BackgroundGeolocationService has hard-coded settings

### ISSUE THREAD

**Issue by yomatters** [CUUATS/bikemoves#9]
For example:

```
      config.configureUrl = 'http://192.168.11.120:8080/configure';
      config.configureInterval = 10000;
      config.extras = {
        "foo": "extra data item"
      };
```

Actually, all of the settings machinery in the service seems to be related to the settings UI in the sample app and probably is unnecessary.

**Comment by afekete** [comment]
I'm fairly certain those settings are used by the geolocation plugin and the settings UI was just to show that the settings can be changed programatically.
I removed the specific code that you used as an example but when I skimmed the rest it all looked useful (not all used at the moment though)
f70e964f988d9e17c3ca7030b5693bd08c5bbea8
